# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f86a441e865b20bbd82b142a6cccd2c01db8dcf9e95aa91405b9cfed3a1c385171d70f78300fed810f0ff29ee8d13664317dca0a2c5abe2541c27574acd05689

test:
  secret_key_base: 9f81191296c983d465f7c0ffd26ce365a6ab4ebba114bf8714161ebb50613beafcc27e7df5bb30b62fda069d7c6be575014ebd4613dd800915aeac12d575aa54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
